### PR TITLE
ADD chroma bin

### PR DESCRIPTION
**Pull request by ndelangen**
I added a `chroma` bin.

### CODE REVIEW

**Comment by ndelangen** [comment]
I did not know that existed 😮

**Comment by ndelangen** [comment]
Do you mean `chroma publish`?
https://github.com/chromaui/chromatic/tree/c43502a275d1e207f132139594e17fbde6f295cf/packages/storybook-chromatic/src/bin

**Comment by ndelangen** [comment]
Then yes, since that command did nothing different from test

**Comment by tmeasday** [comment]
Ahh, sorry!! Yes I meant `publish`, and yes it should do the same thing. Damn I meant to send this to you last night, sorry!

**Pull request merged**
