### PR TITLE
Add additional logging for turbosnap

### PR DESCRIPTION
**Pull request by ethriel3695**
I added some debug logging for the traced Files and affected Modules to assist with debugging CI configurations where we are not able to trace files, even with `storybookBaseDir` and `storybookConfigDir`

### CODE REVIEW

**Review by ghengeveld — APPROVED** [review]

**Comment by tmeasday** [comment]
@ethriel3695 can you share some examples of what the logs look like?

The things I would like to see added are:

1. `baseDir` and `storybookConfigDir`
2. Tracing when `preview.js` etc are matched

**Comment by ethriel3695** [comment]
@tmeasday 

I took some screenshots of what the Logs look like with a Base and Config directory, and if there is no trace as well as when a trace is successful.

Screen Shot 2023-06-06 at 7 45 23 AM
Screen Shot 2023-06-06 at 7 47 05 AM

I'm also logging what the normalized path looks like.
One is with a `baseDir` specified. In my example, it's `subdir`.

Screen Shot 2023-06-06 at 8 13 07 AM
Screen Shot 2023-06-06 at 8 13 27 AM

**Comment by tmeasday** [comment]
Should it be logging the same normalized paths so many times?

**Comment by ethriel3695** [comment]
> Should it be logging the same normalized paths so many times?

I've tried a few different options for logging the normalized path, and honestly, I don't love any of the iterations.

What do you think about removing that from the debug log?

**Comment by tmeasday** [comment]
I think it's better not to have it than to spam it like that.

**Comment by ethriel3695** [comment]
@tmeasday I removed the excessive logs.

**Review by tmeasday — COMMENTED** [review]
LGTM lets get this merged

**Review by tmeasday — APPROVED** [review]
LGTM lets get this merged

**Pull request merged**
