### PR TITLE
Prevent non-string or null message in timestamp logging from causing exit code 254 during build.

### PR DESCRIPTION
**Pull request by BenjaminEllisSo**
Prevent non-string or null message from causing exit code 254 during build.

### CODE REVIEW

**Comment by andrewortwein** [comment]
@BenjaminEllisSo is there a specific scenario to reproduce this issue? Just curious how you might have hit this problem.

**Review by ghengeveld — APPROVED** [review]

**Comment by JonathanKolnik** [comment]
@BenjaminEllisSo here is a canary version with your fix, can you confirm it's working as expected


<details>
  <summary>📦 Published PR as canary version: <code>11.0.2--canary.939.8160747355.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install chromatic@11.0.2--canary.939.8160747355.0
  # or 
  yarn add chromatic@11.0.2--canary.939.8160747355.0
  ```
</details>

**Comment by ghengeveld** [comment]
:rocket: PR was released in [`v11.0.7`](https://github.com/chromaui/chromatic-cli/releases/tag/v11.0.7) :rocket:

**Comment by BenjaminEllisSo** [comment]
Pulled and tested. That resolved it - thank you!!!

**Comment by ghengeveld** [comment]
Excellent! Thanks for helping out!

**Pull request merged**
