### PR TITLE
Replace release script with auto shipit

### PR DESCRIPTION
**Pull request by ghengeveld**
Not ready yet, needs to handle GitHub Action releasing.

<details>
  <summary>📦 Published PR as canary version: <code>7.2.1--canary.828.99e7734.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install chromatic@7.2.1--canary.828.99e7734.0
  # or 
  yarn add chromatic@7.2.1--canary.828.99e7734.0
  ```
</details>

### CODE REVIEW

**Review by thafryer — APPROVED** [review]
LGTM!

**Review by tmeasday — COMMENTED** [review]
Looks good apart from the action part -- looks like it published this PR to `v1`?

https://github.com/chromaui/chromatic-cli/actions/runs/6397978376/job/17367105473?pr=828

**Comment by ghengeveld** [comment]
> Looks good apart from the action part -- looks like it published this PR to `v1`?
> 
> [chromaui/chromatic-cli/actions/runs/6397978376/job/17367105473?pr=828](https://github.com/chromaui/chromatic-cli/actions/runs/6397978376/job/17367105473?pr=828)

`v1` is the tag we use right now, always. It's the one that's linked to our [Marketplace release](https://github.com/chromaui/action/releases/tag/v1).

I'm punting on the other (semver) tags for now. Let's get this operational before we make any actual changes to the final release. As implemented it's the same as it was before.

**Comment by tmeasday** [comment]
@ghengeveld but that means every PR will get pushed to `v1` right now.

**Comment by ghengeveld** [comment]
@tmeasday For action-canary, yes. Perhaps we shouldn't auto-release that one but only do manual releases. I'll update that.

**Pull request merged**
