### PR TITLE
GitHub action to add package size comment to PR

### PR DESCRIPTION
**Pull request by jmhobbs**
We can later adapt this to track +/- changes over previous release.

<details>
  <summary>📦 Published PR as canary version: <code>11.10.3--canary.1040.10851820355.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install chromatic@11.10.3--canary.1040.10851820355.0
  # or 
  yarn add chromatic@11.10.3--canary.1040.10851820355.0
  ```
</details>

### CODE REVIEW

**Comment by jmhobbs** [comment]
I've got a version of this which generates a flame graph image of the esbuild analysis, but I need somewhere to stash the image.  If we want that, I can make an S3 bucket with public read in a follow up PR.

e.g.: 
screenshot

**Review by codykaup — APPROVED** [review]
I tried to figure out if the API offers a way to upload images (similar to pasting one in a comment) but that's a no. 😭 

This is a great start!

**Comment by jmhobbs** [comment]
> I tried to figure out if the API offers a way to upload images (similar to pasting one in a comment) but that's a no. 😭
> 
> This is a great start!

Yeah, I looked at actions assets but it always bundles them into zips 😢

**Comment by ghengeveld** [comment]
:rocket: PR was released in [`v11.10.3`](https://github.com/chromaui/chromatic-cli/releases/tag/v11.10.3) :rocket:

**Pull request merged**
