### PR TITLE
Add various counts as GitHub Action outputs

### PR DESCRIPTION
**Pull request by SiTaggart**
Add the changeCount from the current Chromatic build to the output from the GitHub action.

### CODE REVIEW

**Comment by ndelangen** [comment]
@ghengeveld WDTY about this?
1 problem I see is that this will likely not won't work when the `--exit-once-uploaded` is set.

**Comment by SiTaggart** [comment]
Any movement on this? We'd love to have this unblock a workflow for us @ndelangen @ghengeveld

**Review by ghengeveld — APPROVED** [review]

**Comment by ghengeveld** [comment]
I added a bunch of other counts as well. Good stuff 👍

**Comment by SiTaggart** [comment]
Hi @ghengeveld @ndelangen 

Do you have an ETA on when this will merge and get released to the CLI and Github Action?

Thanks

**Comment by ndelangen** [comment]
@ghengeveld I think we should just merge and release this. Do you know of anything blocking this?

**Comment by ghengeveld** [comment]
@SiTaggart in case you didn't know already, these fields should all be available now.

**Comment by SiTaggart** [comment]
Yeah, this is amazing. Thank you

**Pull request merged**
