### PR TITLE
ADD unfetch as a fetch polyfill, as it's not in JSDom by default?

### PR DESCRIPTION
**Pull request by ndelangen**
issue: https://github.com/chromaui/chromatic-cli/issues/14
docs for polyfill: https://github.com/developit/unfetch
not included in jsdom yet: https://github.com/jsdom/jsdom/issues/1724

### CODE REVIEW

**Comment by ndelangen** [comment]
Haven't tested this yet

**Comment by tmeasday** [comment]
🤔 @ndelangen we don't really need the code to *work* just not error. Usually with these "shims" I would include way less code than this.

**Comment by ndelangen** [comment]
So you'd rather have

```js
window.fetch = () => new Promise()
```

?

**Comment by tmeasday** [comment]
I think so. Do you anticipate problems with that?

**Comment by ndelangen** [comment]
Yeah if we ever allow async stories in storybook, we may need fetch in JSdom

**Comment by ndelangen** [comment]
@tmeasday I changed it to a pure shim

**Pull request merged**
