### PR TITLE
Set commit details when using env var and warn if it's missing

### PR DESCRIPTION
**Pull request by ghengeveld**
When passing the commit SHA using an environment variable (either explicitly or by using GitHub Actions or Travis), also set the committer name / email or show a warning when the given commit isn't found in history.

### CODE REVIEW

**Comment by ghengeveld** [comment]
Should add tests.

**Comment by yannbf** [comment]
Can you add a test for the scenario you wrote?

**Comment by ghengeveld** [comment]
Added a slew of tests.

**Comment by ghengeveld** [comment]
This was released in 6.3.0.

**Pull request merged**
