### PR TITLE
Release review PR

### PR DESCRIPTION
**Pull request by ndelangen**
fixes: #65
fixes: #66
fixes: #62 
fixes: #14
fixes: #27
fixes: #58

### CODE REVIEW

**Comment by tmeasday** [comment]
Found two issues in QA:
 - https://github.com/chromaui/chromatic-cli/issues/65
 - https://github.com/chromaui/chromatic-cli/issues/66

**Comment by tmeasday** [comment]
Also can you update the Changelog in this PR

**Comment by ndelangen** [comment]
@tmeasday I think this is good to go now. I fixed the 2 problems you reported.

I finally found the origin of the buffer, and stringified it to show the proper message

**Comment by tmeasday** [comment]
@ndelangen 

1. I am still not seeing the git error message:

image

[ I think the problem here is that the message is "fatal: not a git repository (or any of the parent directories): .git" (note the case on "not")]

2. You shouldn't be able to pass `-s` (or `--script-name`) and `--exit-once-uploaded`.

**Comment by ndelangen** [comment]
final approval @tmeasday ?

**Comment by tmeasday** [comment]
Go for it!

**Pull request merged**
