### PR TITLE
179/fix for no history in actions

### PR DESCRIPTION
**Pull request by ndelangen**
issue: https://github.com/chromaui/chromatic-cli/issues/179

check for a second commit, and if it doesn't exists throw and error

### CODE REVIEW

**Comment by ghengeveld** [comment]
Damn, looks like we both worked on this: https://github.com/chromaui/chromatic-cli/pull/207

**Comment by ghengeveld** [comment]
@ndelangen I like your way of checking the number of commits using `git log --max-count=1 --skip=1`. That seems more efficient than running a command to get the total number of commits like I did.

What I didn't like about your solution is that it throws when there's only one commit, while mine only warns. Technically a repo with only one commit _is_ valid and possible. It's just unlikely to be true.

@tmeasday Do you think we should warn or fail if we find there's only one commit?

FYI we [already fail](https://github.com/chromaui/chromatic-cli/blob/152dc03ad70d00ba79516f89f7b6ed14f0453d99/bin/git/git.js#L35) if there's zero commits. No need to handle that scenario any different.

**Comment by tmeasday** [comment]
> @tmeasday Do you think we should warn or fail if we find there's only one commit?

We decided to **fail**. It's just infinitely more common that someone is using a CI system that only checks out the current commit that somehow a user is using a repo with only one commit in it [1]. 

I think as long as the message says something like "if you legitimately only have one commit in this repo, make another one and run chromatic again".


[1] I suspect this will only ever happen to us during QA.

**Comment by ghengeveld** [comment]
Alright. I've updated my PR with the following:
- Used Norbert's `-n 1 --skip=1` trick to find the previous commit rather than the total count. We don't really need the count anyway.
- Updated all git error messaging to use the UI patterns that we have (and create stories for them)
- Changed the shallow clone warning to an error, so it'll fail.

Closing this in favor of #207.

**Pull request closed without merging**
