### PR TITLE
Allow Github merge queues

### PR DESCRIPTION
**Pull request by mhemmings**
Add the `merge_group` event to the supported Github Action events to support merge queues. 

Request body from the [docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads#merge_group), but any help testing would be greatly appreciated!

Fixes https://github.com/chromaui/chromatic-cli/issues/741

### CODE REVIEW

**Comment by thafryer** [comment]
@mhemmings This looks good. I'll try to cut a release to test this with by end of week. We are at the company meetup so comms will be delayed.

**Comment by thafryer** [comment]
@mhemmings I released a version of this for testing. You should be able to confirm this works by replacing `uses: chromaui/action@v1 `with `uses: chromaui/action-next@v1`

**Comment by mhemmings** [comment]
Hi @thafryer, sorry I've only just got round to checking this out. Does `chromaui/action-next@v1` still have this change shipped with it?

**Comment by thafryer** [comment]
> Hi @thafryer, sorry I've only just got round to checking this out. Does `chromaui/action-next@v1` still have this change shipped with it?

@mhemmings Yes, it currently has the change! Please try it out!

**Comment by thafryer** [comment]
@mhemmings We rolled this out v7.6.0! Thanks for the contribution!

**Pull request closed without merging**
