### PR TITLE
Add --exit-once-sent-to-chromatic flag

### PR DESCRIPTION
**Pull request by benjaminkay93**
Added the flag, not sure how to test it locally to ensure that it works, would be a help if someone could advise, perhaps its just an npm link? 

This is raised as part of #62

### CODE REVIEW

**Comment by tmeasday** [comment]
This is awesome @benjaminkay93!

**Comment by tmeasday** [comment]
Hi @benjaminkay93, so I think our process is to check in the build `dist` directory as well (@ndelangen I think we were going to add some checks for this, should we make an issue for that?)

If you do that, you should be able to run this branch against any app by doing something like `yarn add benjaminkay93/chromatic-cli#master`

**Comment by tmeasday** [comment]
OK, here's what I'm thinking about this:

1. Let's call the flag `--exit-once-uploaded`?
2. You shouldn't be able to use this flag and use the tunnel, so it should error if you set it and `--script-name` or `--do-not-start`.

**Comment by benjaminkay93** [comment]
Yeah that's about right, thanks for sorting that for me :) 🚀

When will it be published?

**Comment by ndelangen** [comment]
Should be released today or tomorrow!

**Pull request merged**
