### PR TITLE
Support `workflow_dispatch` event in GitHub Action

### PR DESCRIPTION
**Pull request by lyleunderwood**
#307

I was trying to setup a manual chromatic runner using github actions via a github bot, and I wanted to use `workflow_dispatch` but this action didn't seem to allow it. I went ahead and added basic support.

### CODE REVIEW

**Comment by lyleunderwood** [comment]
It seems like chromatic only ever wants just the branch name, never the full ref (`refs/heads/my-branch`). Providing the full ref seems to result in chromatic always failing to compare to master. Does anybody have any insight into this point? Is there any reason I'd ever want to allow the full ref to pass through?

**Comment by ndelangen** [comment]
@lyleunderwood could you elaborate this question:

> Is there any reason I'd ever want to allow the full ref to pass through?

**Comment by ghengeveld** [comment]
@lyleunderwood That's right, we basically never expect to see `refs/heads/`. We strip that off [right here](https://github.com/chromaui/chromatic-cli/blob/701f7c8244b419a8b80b5a33a12392c8ea0ef351/bin/git/git.js#L117). Arguably the way we do it is slightly safer because the regex ensures it only strips it at the start of the string, never somewhere half way. It's unlikely someone would have an actual branch name like that, but theoretically possible.

@ndelangen Can you judge whether workflow_dispatch is safe for us to allow?

**Comment by ndelangen** [comment]
> Can you judge whether workflow_dispatch is safe for us to allow? If so, I think this is a nice improvement.

Shall we add a test workflow in this repo and test it.

**Comment by lyleunderwood** [comment]
Hey, sorry I've been on vacation :tropical_drink: 

I went ahead and updated the README to reflect that we really just want a regular branch name.

As for stripping off the ref prefix, it's currently just based on what's being done in the `push` case, let me know if I should remove it.

https://github.com/chromaui/chromatic-cli/blob/71e3c9639e735699d7fe6ebbd89a4bff10ecf747/action/main.ts#L42

**Comment by Manubi** [comment]
Will this get merged any time soon? :)

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
