### PR TITLE
Deprecate `--preserve-missing` and raise a warning if it's being used

### PR DESCRIPTION
**Pull request by ghengeveld**
Screen Shot 2022-08-17 at 15 00 47

### CODE REVIEW

**Review by ShaunLloyd — APPROVED** [review]
Looks good, @ghengeveld!

**Review by thafryer — APPROVED** [review]
LGTM! I'll create a ticket to remove it for v7.0.0 .

**Comment by adybionka** [comment]
Where can I find more information, on why this flag is going to be deprecated? 

It will be possible to send only a subset of stories Chromatic, and the rest will be considered as unchanged?

**Comment by ghengeveld** [comment]
We're working on the updated documentation for this. Should be out soon. I'll also update the changelog with some details.

The gist is that preserveMissing is troublesome when upgrading capture infrastructure, makes baseline logic more complicated and leads to stories never getting removed from Chromatic. As a replacement we offer TurboSnap (`onlyChanged`), `onlyStoryFiles` and `onlyStoryNames` (previously `only`).

**Pull request merged**
